#Setting DB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://118.67.142.143:3306/nooblol?characterEncoding=UTF-8&serverTimezone=UTC
    username: nooblol
    password: nooblol_dba
    tomcat:
      validation-query: SELECT 1 FROM DUAL

  #redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8081


#log
logging:
  file:
    path: /nooblol/app/log
    name: nooblol.log
  level:
    root: debug