#Setting DB
spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    # More Detail Query Log
    url: ${MariaDB-URL}
    username: ${Database-UserName}
    password: ${Database-Password}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      validation-query: SELECT 1 FROM DUAL
  redis: #redis
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-id}
    password: ${mail-Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Embedded Tomcat Session TimeOut
server:
  servlet:
    session:
      timeout: 3600

#Setting MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    multiple-result-sets-enabled: false
  type-aliases-package: com.nooblol.*.*
  mapper-locations: classpath:mybatis/mapper/*/*.xml

#log
logging:
  file:
    name: nooblol.log
    path: log/local
  level:
    root: info
